const serviceUrls = {
  LOGIN: `authdemograph/auth/login`,
  VERSION_CHECK: `authdemograph/auth/versionCheck`,
  GET_LEAD: `authdemograph/lead/getLead?appId=`,
  SAVE_OR_UPDATE_LEAD: `authdemograph/lead/saveOrUpdateLead`,
  VIEW_LEADS: 'authdemograph/lead/viewLead?',
  GET_CUSTOMER_TYPE: 'authdemograph/lead/getCustomerType',
  VIEW_PROSPECT: `authdemograph/lead/viewProspect?`,
  SAVE_IMAGE: `authdemograph/lead/saveImage`,
  GET_CUSTOMER_PROFILE: `authdemograph/lead/getCustomerProfile`,
  GET_PINCODE: `authdemograph/lead/getPinCode?Pincode=`,
  GENERATE_OTP: `authdemograph/mobile-otp/generateOtp`,
  VALIDATE_OTP: `authdemograph/mobile-otp/validateOtp`,
  GET_CKYC_STATUS: `authdemograph/ckyc/getCKYCStatus`,
  GET_CKYC: `authdemograph/ckyc/getCKYC`,
  GET_PAN_OCR: `authdemograph/ocr/pan/getocrdetails`,
  VERIFY_PAN: `authdemograph/ocr/getPanProfileDetails`,

  GET_AADHAR_OCR: `authdemograph/ocr/aadhar/getocrdetails`,
  SAVE_PAN_DETAILS: `authdemograph/ocr/pan/save`,
  SAVE_AADHAR_DETAILS: `authdemograph/ocr/aadhar/save`,
  GET_AADHAR_DETAILS: `authdemograph/ocr/aadhar/getdetails`,
  GET_PAN_DETAILS: `authdemograph/ocr/pan/getdetails`,
  GET_EXISTING_AADHAR_DETAILS: `authdemograph/aadhaarApi/getExitingAadhaarDeatils`,
  GET_AADHAR_OTP: `authdemograph/aadhaarApi/getAadhaarOtp`,
  GET_AADHAR_DETAILS_BY_OTP: `authdemograph/aadhaarApi/getAadhaarDeatilsByOtp`,
  SAVE_OVD_DETAILS: 'authdemograph/ovd/addOvdDetils',
  GET_OVD_DETAILS: 'authdemograph/ovd/getOvdDetils/',
  ADD_PERMANENT_ADDRESS: `authdemograph/address/addPermanentAddress`,
  ADD_CURRENT_ADDRESS: `authdemograph/address/addCurrentAddress`,
  GET_ADDRESS_DETAILS: `authdemograph/address/getAddressDetails`,
  GET_DEDUPE_DETAILS: `authdemograph/dedupe/dedupeRule`,

  GET_IP_MASTER: `authdemograph/product/getIpMasters`,
  GET_ASSET_MASTER: `authdemograph/master/getAssetDocumentMaterDetails`,
  GET_Relation_MASTER: `authdemograph/product/getRelationship`,
  UPLOAD_PRODUCT_DOCUMENT: 'authdemograph/product/uploadDocumentDetails',
  GET_PRODUCT_DETILS: `authdemograph/product/getDocumentDetails/`,
  SET_PRODUCT_DETILS: `authdemograph/product/addProduct`,
  GET_CRIFF_RESPONSE: `authdemograph/bureauapi/getCriffResponse`,
  GET_VEHICAL_TYPE: `authdemograph/lead/getVechileType`,
  GET_SCHEME_DETAILS: `authdemograph/scheme/getSchemeDetails`,
  GET_ALL_BRANCH: `authdemograph/branch/getAllBranchDetails`,
  GET_MANUFACTURE: `authdemograph/lead/getVechileManufacture`,
  GET_MODEL: `authdemograph/lead/getVechileModel`,
  GET_INSURANCE_CAP: `authdemograph/loan/getInsuranceCap`,
  GET_DELAR: `authdemograph/lead/getDealerName`,
  GET_SUB_DELAR: `authdemograph/lead/getSubDealerName`,
  GET_ALL_SCHEME_DETAILS: `authdemograph/scheme/getSchemeDeatilsByAppId`,
  GET_ROAD_TAX_DETAILS: `authdemograph/master/getRoadtax`,
  GET_TENURE: `authdemograph/scheme/getTenureDetailsBySchemeId`,
  GET_EMI_VALUE: `authdemograph/emi/calculateEmi`,
  GET_PLI_VALUE: `authdemograph/loan/getPli`,
  SET_DELARSHIP_DETAILS: `authdemograph/loan/addDearshipDetails`,
  GET_DELARSHIP_DETAILS: `authdemograph/loan/getDearshipDetails`,
  SET_LOAN_DETAILS: `authdemograph/loan/saveLoan`,
  GET_LOAN_DETAILS: `authdemograph/loan/getLoanDetails`,
  GET_BRANCH: `authdemograph/lead/getAllBranchDetails`,
  GET_SANCTION_LETTER_DETAILS: `authdemograph/lead/getSoftOfferDetails/`,
  GET_FRANCSIES: `authdemograph/master/getAllFranchise`,
  GET_EXTERNALLEAD: `authdemograph/loan/getExternalLeadDropDown`,
  REMOVE: 'authdemograph/lead/delete?',
  GET_BRE1_STATUS: 'authdemograph/ruleengineapi/getbre1status?',
  GET_BRE2_STATUS: 'authdemograph/ruleengineapi/getbre2status?',
  GET_BRE3_STATUS: 'authdemograph/ruleengineapi/getbre3status',
  ACCOUNT_AGGREGATOT: `authdemograph/accAgreegator/getAccountAggregator`,
  GET_EMPLOYMENT_DETAILS: `authdemograph/employment/getEmploymentDetails/`,
  SAVE_EMPLOYMENT_DETAILS: `authdemograph/employment/addEmploymentDetails`,
  GET_FAMILY_NON_FAMILY_DATA: `authdemograph/relationship/getFamilyNonFamilyData`,
  GET_RELATIONSHIP_MASTER: `authdemograph/relationship/getRelationMaster`,
  SAVE_FAMILY_NON_FAMILY_DATA: `authdemograph/relationship/saveFamilyNonFamilyData`,
  VIEW_STATUS: `authdemograph/lead/viewStatus?appId=`,
  GENERATE_SANCTION_LETTER : `authdemograph/generateSactionLetter?applicantId=`,
  GET_SANCTION_LETTER : `authdemograph/getSanctionLetter?applicantId=`,
  SEND_OTP_SANCTION_LETTER: `authdemograph/sendOtpForSanctionLetter?`,
  VERIFY_OTP_SANCTION_LETTER: `authdemograph/verifyOtpForSanctionLetter`,
  PENNY_DROP:`authdemograph/pennydrop/verify`,
  GET_PENNY_DROP_DETAILS:`authdemograph/pennydrop/get-pennyDrop`,
  SAVE_MANUAL_OVD_DETAILS:`authdemograph/ovd/saveManualOvdDetils`,
  SAVE_REPAYMENT_DETAILS: `authdemograph/repayment/saverepayment`,
  SAVE_CASH_DETAILS: `authdemograph/branch/saveCashDetails`,
  //GET_PHYSICAL_NACH: `authdemograph/wrapper/autofillEnachPdf`,
  GET_PHYSICAL_NACH: `authdemograph/wrapper/idfcPhysicalNachRegister`,
  DELETE_PHYSICAL_NACH: `authdemograph/wrapper/deleteUploadedAutofillEnach`,
  UPLOAD_PHYSICAL_NACH: `authdemograph/wrapper/autofillEnachUpload`,

  GET_CASH_DETAILS: `authdemograph/branch/getCashDetails`,
  GET_APPLICATION_DETAILS: `authdemograph/repayment/getApplicantDetailsForCampsPayEnach`,
  GET_REPAYMENT_DETAILS: `authdemograph/repayment/getRepaymentDetails?applicantUniqueId=`,
  GET_CAMSPAY_ENACH_RESPONSE: `authdemograph/repayment/getCamsPayEnachResponse`,
  REGISTER_REPAYMENT_DETAILS: `authdemograph/wrapper/register-enach`,
  VALIDATE_VPA: `authdemograph/wrapper/validate-vpa`,
  CREATE_MANDATE_VPA: `authdemograph/wrapper/create-mandate-for-vpa`,
  GET_DOCUMENTS:`authdemograph/product/getDocumentDetails`,
  UPLOAD_DOCUMENTS:`authdemograph/document/uploadDocument`,
  DELETE_DOCUMENT:`authdemograph/document/deleteUploadDocument`,
  GET_PRE_DOCUMENT_DETAIL:`authdemograph/master/getpreDocumetDetail/Pre_Disbursal/`,
  GET_DEVIATION_DOCUMENT_DETAIL:`authdemograph/loan/getDeviationDetails`,
  UPLOAD_DEVIATION_DOCUMENTS:`authdemograph/deviation/uploadDocument`,
  SALES_REJECT:`authdemograph/deviation/salesRejected`,
  SALES_REEDIT:`authdemograph/lead/isEdit`,

  GET_PREOFFER:`authdemograph/lead/getDedupeCustomerApi`,
  GET_APPLICANT_DETAILS_BY_AADHAR:`authdemograph/lead/getApplicantDetailsByAadhaar`,
  GET_SHERLOCK_RESPONSE:`authdemograph/bureauapi/getSherlockResponse`,
  GET_CONSTITUTION:`authdemograph/master/getConstitutionMasterDetails`,
  UPLOAD_POST_DISBURSAL_DOCUMENTS:`authdemograph/postDisbursal/uploadDocument`,
  UPLOAD_POST_DISBURSAL_PAN_OCR: `authdemograph/ocr/pan/getocrdetailspre`,
  UPLOAD_POST_DISBURSAL_AADHAR_OCR: `authdemograph/ocr/aadhar/getocrdetailspre`,
  DELETE_POST_DISBURSAL_DOCUMENT:`authdemograph/postDisbursal/deleteDocument`,
  GET_POST_DOCUMENT_DETAIL:`authdemograph/postDisbursal/getDocument`,
  SAVE_VEHICLE_COLLATERAL_INFO: `authdemograph/postDisbursal/savePostDisbursalVehicleDetails`,
  GET_BRANCHES:`authdemograph/lead/getBranch`,
  GET_TERMS_AND_CONDITIONS:`authdemograph/lead/getTermsAndCondition`,
  UPLOAD_DEFERAL_DOCUMENT:`authdemograph/document/uploadDeferelDocument`,
  GET_DEFERAL_DOCUMENTS:`authdemograph/deferaldocument/getDeferalDocument/mainApplicant/`,
  DELETE_DEFERAL_DOCUMENT:`authdemograph/document/deleteDeferealDocument`,
  GET_CREDI_TO_SUBMIT_DETAILS: `authdemograph/employment/submitToCredit/`,
  SAVE_PSD_INFO: `authdemograph/invoice/saveInvoiceDetails`,
  GET_PSD_INFO:`authdemograph/invoice/getInvoiceDetails`,
  GET_PSD_INFO_WITH_IP: `authdemograph/invoice/getInvoiceDetailsWithIPBranch`,
  GET_INSURANCE_COMPANY_MASTER: `authdemograph/master/getInsuranceMasterList`,
  SUBMIT_TO_DISBUSTMENT: `authdemograph/credit/submitToDisbursment`,
  ESIGN_LOAN_AGREEMENT: `authdemograph/signagreementapi/esignRequest`,
  GET_LOAN_AGREEMENT_DETAILS: `authdemograph/signagreementapi/getAgreementDetails?`,
};

export default serviceUrls;