const plServiceUrls = {
  LOGIN: `authdemograph-pl/auth/login`,
  VERSION_CHECK: `authdemograph-pl/auth/versionCheck`,
  GET_PL_COUNT: 'authdemograph-pl/lead/getProspectCount',
  GET_LEAD: `authdemograph-pl/lead/getLead?appId=`,
  SAVE_OR_UPDATE_LEAD: `authdemograph-pl/lead/saveOrUpdateLead`,
  VIEW_LEADS: 'authdemograph-pl/lead/viewLead?',
  GET_CUSTOMER_TYPE: 'authdemograph-pl/lead/getCustomerType',
  VIEW_PROSPECT: `authdemograph-pl/lead/viewProspect?`,
  SAVE_IMAGE: `authdemograph-pl/lead/saveImage`,
  GET_CUSTOMER_PROFILE: `authdemograph-pl/lead/getCustomerProfile`,
  GET_REFRENCE: `authdemograph-pl/dropdown/getDropdownByType`,

  GET_PINCODE: `authdemograph-pl/lead/getPinCode?Pincode=`,
  GENERATE_OTP: `authdemograph-pl/mobile-otp/generateOtp`,
  VALIDATE_OTP: `authdemograph-pl/mobile-otp/validateOtp`,
  GET_CKYC_STATUS: `authdemograph-pl/ckyc/getCKYCStatus`,
  GET_CKYC: `authdemograph-pl/ckyc/getCKYC`,
  GET_PAN_OCR: `authdemograph-pl/ocr/pan/getocrdetails`,
  VERIFY_PAN: `authdemograph-pl/ocr/getPanProfileDetails`,
  GET_DEDUPES_DETAILS: `authdemograph-pl/dedupe/dedupeRuleNew`,
  GET_LEAD_SOURCE: `authdemograph-pl/leadBusinessSource/getLeadSource`,
  GET_LEAD_BUSINESS_VERTICAL: `authdemograph-pl/leadBusinessSource/getLeadBusinessVerticle`,
  GET_VERIFY_EMPLOYEE: `authdemograph-pl/salesApi/verify-employee`,

  GET_AADHAR_OCR: `authdemograph-pl/ocr/aadhar/getocrdetails`,
  SAVE_PAN_DETAILS: `authdemograph-pl/ocr/pan/save`,
  SAVE_AADHAR_DETAILS: `authdemograph-pl/ocr/aadhar/save`,
  GET_AADHAR_DETAILS: `authdemograph-pl/ocr/aadhar/getdetails`,
  GET_PAN_DETAILS: `authdemograph-pl/ocr/pan/getdetails`,
  GET_EXISTING_AADHAR_DETAILS: `authdemograph-pl/aadhaarApi/getExitingAadhaarDeatils`,
  GET_AADHAR_OTP: `authdemograph-pl/aadhaarApi/getAadhaarOtp`,
  GET_AADHAR_DETAILS_BY_OTP: `authdemograph-pl/aadhaarApi/getAadhaarDeatilsByOtp`,
  SAVE_OVD_DETAILS: 'authdemograph-pl/ovd/addOvdDetils',
  GET_OVD_DETAILS: 'authdemograph-pl/ovd/getOvdDetils/',
  ADD_PERMANENT_ADDRESS: `authdemograph-pl/address/addPermanentAddress`,
  ADD_CURRENT_ADDRESS: `authdemograph-pl/address/addCurrentAddress`,
  GET_ADDRESS_DETAILS: `authdemograph-pl/address/getAddressDetails`,
  GET_DEDUPE_DETAILS: `authdemograph-pl/dedupe/dedupeRule`,

  GET_IP_MASTER: `authdemograph-pl/product/getIpMasters`,
  GET_ASSET_MASTER: `authdemograph-pl/master/getAssetDocumentMaterDetails`,
  GET_Relation_MASTER: `authdemograph-pl/product/getRelationship`,
  UPLOAD_PRODUCT_DOCUMENT: 'authdemograph-pl/product/uploadDocumentDetails',
  GET_PRODUCT_DETILS: `authdemograph-pl/product/getDocumentDetails/`,
  SET_PRODUCT_DETILS: `authdemograph-pl/product/addProduct`,
  GET_CRIFF_RESPONSE: `authdemograph-pl/bureauapi/getCriffResponse`,
  GET_RETRY_CRIFF_RESPONSE: `authdemograph-pl/sherlock/breCalling`,

  GET_VEHICAL_TYPE: `authdemograph-pl/lead/getVechileType`,
  GET_SCHEME_DETAILS: `authdemograph-pl/scheme/getSchemeDetails`,
  GET_ALL_BRANCH: `authdemograph-pl/branch/getAllBranchDetails`,
  GET_MANUFACTURE: `authdemograph-pl/lead/getVechileManufacture`,
  GET_MODEL: `authdemograph-pl/lead/getVechileModel`,
  GET_INSURANCE_CAP: `authdemograph-pl/loan/getInsuranceCap`,
  GET_DELAR: `authdemograph-pl/lead/getDealerName`,
  GET_SUB_DELAR: `authdemograph-pl/lead/getSubDealerName`,
  GET_ALL_SCHEME_DETAILS: `authdemograph-pl/scheme/getSchemeDeatilsByAppId`,
  GET_ROAD_TAX_DETAILS: `authdemograph-pl/master/getRoadtax`,
  GET_TENURE: `authdemograph-pl/scheme/getTenureDetailsBySchemeId`,
  GET_EMI_VALUE: `authdemograph-pl/emi/calculateEmi`,
  GET_PLI_VALUE: `authdemograph-pl/loan/getPli`,
  SET_DELARSHIP_DETAILS: `authdemograph-pl/loan/addDearshipDetails`,
  GET_DELARSHIP_DETAILS: `authdemograph-pl/loan/getDearshipDetails`,
  SET_LOAN_DETAILS: `authdemograph-pl/loan/saveLoan`,
  GET_LOAN_DETAILS: `authdemograph-pl/loan/getLoanDetails`,
  GET_BRANCH: `authdemograph-pl/lead/getAllBranchDetails`,
  GET_SANCTION_LETTER_DETAILS: `authdemograph-pl/lead/getSoftOfferDetails/`,
  GET_FRANCSIES: `authdemograph-pl/master/getAllFranchise`,
  GET_EXTERNALLEAD: `authdemograph-pl/loan/getExternalLeadDropDown`,
  GET_HPNUMBER: `authdemograph-pl/dedupe/applicationIds`,

  GENERATE_KFS: `authdemograph-pl/generateKFSDoc`,
  GET_KFS: `authdemograph-pl/getKFSDoc?applicantId=`,
  CALL_LIGALITY: `authdemograph-pl/callLegality`,

  REMOVE: 'authdemograph-pl/lead/delete?',
  GET_BRE1_STATUS: 'authdemograph-pl/ruleengineapi/getbre1status?',
  GET_BRE2_STATUS: 'authdemograph-pl/ruleengineapi/getbre2status?',
  GET_BRE3_STATUS: 'authdemograph-pl/ruleengineapi/getbre3status',
  ACCOUNT_AGGREGATOT: `authdemograph-pl/accAgreegator/getAccountAggregator`,
  GET_EMPLOYMENT_DETAILS: `authdemograph-pl/employment/getEmploymentDetails/`,
  SAVE_EMPLOYMENT_DETAILS: `authdemograph-pl/employment/addEmploymentDetails`,
  GET_FAMILY_NON_FAMILY_DATA: `authdemograph-pl/relationship/getFamilyNonFamilyData`,
  GET_RELATIONSHIP_MASTER: `authdemograph-pl/relationship/getRelationMaster`,
  SAVE_FAMILY_NON_FAMILY_DATA: `authdemograph-pl/relationship/saveFamilyNonFamilyData`,
  VIEW_STATUS: `authdemograph-pl/lead/viewStatus?appId=`,
  GENERATE_SANCTION_LETTER : `authdemograph-pl/generateSactionLetter`,
  GET_SANCTION_LETTER : `authdemograph-pl/getSanctionLetter?applicantId=`,
  SEND_OTP_SANCTION_LETTER: `authdemograph-pl/sendOtpForSanctionLetter?`,
  VERIFY_OTP_SANCTION_LETTER: `authdemograph-pl/verifyOtpForSanctionLetter`,
  PENNY_DROP:`authdemograph-pl/pennydrop/verify`,
  GET_PENNY_DROP_DETAILS:`authdemograph-pl/pennydrop/get-pennyDrop`,
  SAVE_MANUAL_OVD_DETAILS:`authdemograph-pl/ovd/saveManualOvdDetils`,
  SAVE_REPAYMENT_DETAILS: `authdemograph-pl/repayment/saverepayment`,
  SAVE_CASH_DETAILS: `authdemograph-pl/branch/saveCashDetails`,
  //GET_PHYSICAL_NACH: `authdemograph-pl/wrapper/autofillEnachPdf`,
  GET_PHYSICAL_NACH: `authdemograph-pl/wrapper/idfcPhysicalNachRegister`,
  DELETE_PHYSICAL_NACH: `authdemograph-pl/wrapper/deleteUploadedAutofillEnach`,
  UPLOAD_PHYSICAL_NACH: `authdemograph-pl/wrapper/autofillEnachUpload`,

  GET_EMANDATE_BANKLIST: `authdemograph-pl/idfcEnach/emandateBankList`,
  GET_ESIGN_BANKLIST: `authdemograph-pl/idfcEnach/emandateEsignBankList`,

  GET_CASH_DETAILS: `authdemograph-pl/branch/getCashDetails`,
  GET_APPLICATION_DETAILS: `authdemograph-pl/repayment/getApplicantDetailsForCampsPayEnach`,
  GET_REPAYMENT_DETAILS: `authdemograph-pl/repayment/getRepaymentDetails?applicantUniqueId=`,
  GET_CAMSPAY_ENACH_RESPONSE: `authdemograph-pl/repayment/getCamsPayEnachResponse`,
  REGISTER_REPAYMENT_DETAILS:   `authdemograph-pl/idfcEnach/enachregistration`,
  // `authdemograph-pl/wrapper/register-enach`,
  VALIDATE_VPA: `authdemograph-pl/wrapper/validate-vpa`,
  CREATE_MANDATE_VPA: `authdemograph-pl/wrapper/create-mandate-for-vpa`,
  GET_DOCUMENTS:`authdemograph-pl/product/getDocumentDetails`,
  UPLOAD_DOCUMENTS:`authdemograph-pl/document/uploadDocument`,
  DELETE_DOCUMENT:`authdemograph-pl/document/deleteUploadDocument`,
  GET_PRE_DOCUMENT_DETAIL:`authdemograph-pl/master/getpreDocumetDetail/Pre_Disbursal/`,
  GET_DEVIATION_DOCUMENT_DETAIL:`authdemograph-pl/loan/getDeviationDetails`,
  UPLOAD_DEVIATION_DOCUMENTS:`authdemograph-pl/deviation/uploadDocument`,
  SALES_REJECT:`authdemograph-pl/deviation/salesRejected`,
  SALES_REEDIT:`authdemograph-pl/lead/isEdit`,

  GET_PREOFFER:`authdemograph-pl/lead/getDedupeCustomerApi`,
  GET_APPLICANT_DETAILS_BY_AADHAR:`authdemograph-pl/lead/getApplicantDetailsByAadhaar`,
  GET_SHERLOCK_RESPONSE:`authdemograph-pl/bureauapi/getSherlockResponse`,
  GET_CONSTITUTION:`authdemograph-pl/master/getConstitutionMasterDetails`,
  UPLOAD_POST_DISBURSAL_DOCUMENTS:`authdemograph-pl/postDisbursal/uploadDocument`,
  UPLOAD_POST_DISBURSAL_PAN_OCR: `authdemograph-pl/ocr/pan/getocrdetailspre`,
  UPLOAD_POST_DISBURSAL_AADHAR_OCR: `authdemograph-pl/ocr/aadhar/getocrdetailspre`,
  DELETE_POST_DISBURSAL_DOCUMENT:`authdemograph-pl/postDisbursal/deleteDocument`,
  GET_POST_DOCUMENT_DETAIL:`authdemograph-pl/postDisbursal/getDocument`,
  SAVE_VEHICLE_COLLATERAL_INFO: `authdemograph-pl/postDisbursal/savePostDisbursalVehicleDetails`,
  GET_BRANCHES:`authdemograph-pl/lead/getBranch`,
  GET_TERMS_AND_CONDITIONS:`authdemograph-pl/lead/getTermsAndCondition`,
  UPLOAD_DEFERAL_DOCUMENT:`authdemograph-pl/document/uploadDeferelDocument`,
  GET_DEFERAL_DOCUMENTS:`authdemograph-pl/deferaldocument/getDeferalDocument/mainApplicant/`,
  DELETE_DEFERAL_DOCUMENT:`authdemograph-pl/document/deleteDeferealDocument`,
  GET_CREDI_TO_SUBMIT_DETAILS: `authdemograph-pl/employment/submitToCredit/`,
  SAVE_PSD_INFO: `authdemograph-pl/invoice/saveInvoiceDetails`,
  GET_PSD_INFO:`authdemograph-pl/invoice/getInvoiceDetails`,
  GET_PSD_INFO_WITH_IP: `authdemograph-pl/invoice/getInvoiceDetailsWithIPBranch`,
  GET_INSURANCE_COMPANY_MASTER: `authdemograph-pl/master/getInsuranceMasterList`,
  SUBMIT_TO_DISBUSTMENT: `authdemograph-pl/credit/submitToDisbursment`,
  ESIGN_LOAN_AGREEMENT: `authdemograph-pl/signagreementapi/esignRequest`,
  GET_LOAN_AGREEMENT_DETAILS: `authdemograph-pl/signagreementapi/getAgreementDetails?`,
};

export default plServiceUrls;